stages:
- name: compile
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: print  ("compile")
  - runScriptConfig:
      image: python:latest
      shellScript: print ("compile-1-2")
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
- name: test
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: date
- name: release
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: print ("success")
    envFrom:
    - sourceName: pipeline-secret
      sourceKey: admin-user
      targetKey: yanyu
  - runScriptConfig:
      image: python:latest
      shellScript: print ("test")
    env:
      hostname: test-server
    envFrom:
    - sourceName: pipeline-secret
      sourceKey: admin-user
      targetKey: yanyu
  - runScriptConfig:
      image: gcc:latest
      shellScript: sada
    envFrom:
    - sourceName: pipeline-secret
      sourceKey: admin-user
      targetKey: yanyu
- name: test1
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: asdasdsa
  - runScriptConfig:
      image: node:latest
      shellScript: sdadsa
    envFrom:
    - sourceName: pipeline-secret
      sourceKey: admin-token
      targetKey: test
timeout: 60
notification: {}
