stages:
- name: compile
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: print  ("compile")
  - runScriptConfig:
      image: python:latest
      shellScript: print ("compile-1-2")
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
- name: test
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: date
- name: release
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: print ("success")
  - runScriptConfig:
      image: python:latest
      shellScript: print ("release")
timeout: 60
notification: {}
