pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  nodeSelector:
    openstack-control-plane: enabled
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.35-5-alpine
    imagePullPolicy: Always
  - name: maven
    image: maven:alpine
"""
    }
  }
  stages {
    stage('Build docker image') {
      steps {
        container('maven') {
          //sh 'cd /root && sleep 100'
          //sh 'dockerd -H tcp://0.0.0.0:2376'
          //sh 'cd /root && docker build -t ubuntu-with-vi-dockerfile .'
          //sh 'cd /root && docker images'
          //sh 'cd /root && sleep 600'
          sh 'mvn -version'
        }
      }
    }
  }
}
